version: '3.4'

services:
  investing-resource-web-application-test:
    image: ghcr.io/lev4and/investing/resource-web-app:test-latest
    ports:
      - "5003:80"
    environment:
      ASPNETCORE_POSTGRES_DB_SERVER: ${POSTGRES_DB_SERVER}
      ASPNETCORE_POSTGRES_DB_SERVER_PORT: ${POSTGRES_DB_TEST_PORT}
      ASPNETCORE_POSTGRES_DB_NAME: ${POSTGRES_DB_TEST_NAME}
      ASPNETCORE_POSTGRES_DB_USER: ${POSTGRES_USER}
      ASPNETCORE_POSTGRES_DB_PASSWORD: ${POSTGRES_PASSWORD}
      ASPNETCORE_SEQ_SERVER: ${BACKEND_RESOURCE_TEST_SEQ_SERVER}

  investing-resource-web-application-seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5345:80"

  investing-vue-js-app-test:
    image: ghcr.io/lev4and/investing/vue-js-app:test-latest
    ports:
      - "5005:8080"

  investing-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./${POSTGRES_DB_DATA_DIR}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_PORT}:5432

  investing-postgres-test:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./${POSTGRES_DB_TEST_DATA_DIR}:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_DB_TEST_PORT}:5432

  investing-pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - investing-postgres
      - investing-postgres-test
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  investing-portainer:
    image: portainer/portainer-ce
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/data
    ports:
      - "9000:9000"

  investing-node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"

  investing-prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  investing-grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3456:3000"

  investing-visualizer:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5006:8080"

  investing-dozzle:
    image: amir20/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"

  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

