global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "investing-prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["investing-prometheus:9090"]

  - job_name: "investing-node-exporter"
    static_configs:
    - targets: ["investing-node-exporter:9100"]