name: Backend Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  http-clients-tests:
    name: HttpClients Unit Test
    runs-on: ubuntu-latest
    env:
      ProjectName: Investing.HttpClients.Tests
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET

      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore $ProjectName

    - name: Build
      run: dotnet build $ProjectName --no-restore

    - name: Test
      run: dotnet test $ProjectName --no-build -l "console;verbosity=normal"