name: Database Backup

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  backup:
    name: Database Backup
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server, build and run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            cd /var/var/projects/Investing/shell
            bash postgresDump.sh
            bash postgresTestDump.sh