name: Docker Service Test Update

on:
  workflow_run:
    workflows: [ Database Test Backup ]
    types: [ completed ]

jobs:
  vue-js-app-update:
    name: update service vue-js-app
    runs-on: ubuntu-latest
    steps:
      - name: Update Docker service
        uses: satak/webrequest-action@master
        with:
          url: http://lev4and.ru/portainer/api/webhooks/62f1fad6-5ade-49c3-8091-a557913e0ef9
          method: POST
  
  resource-web-app-update:
    name: update service resource-web-app
    runs-on: ubuntu-latest
    steps:
      - name: Update Docker service
        uses: satak/webrequest-action@master
        with:
          url: http://lev4and.ru/portainer/api/webhooks/77ca25e5-0bb7-4727-ac6d-410bd6cbb611
          method: POST