name: Docker Image Test Deploy

on:
  push:
    branches: [ master ]

jobs:
  vue-js-app-build:
    name: vue-js-app image build, pull and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: investing-vue-js-app
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/investing/vue-js-app:test-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE $PROJECT_SRC_DIR

      - name: Push docker image
        run: docker push $DOCKER_IMAGE

  resource-web-app-build:
    name: resource-web-app image build, pull and push
    runs-on: ubuntu-latest
    env:
      PROJECT_SRC_DIR: Investing.ResourceWebApplication
      DOCKER_IMAGE: docker.pkg.github.com/lev4and/investing/resource-web-app:test-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to docker.pkg.github.com
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

      - name: Build and pull docker image
        run: docker build -f $PROJECT_SRC_DIR/Dockerfile --pull -t $DOCKER_IMAGE .

      - name: Push docker image
        run: docker push $DOCKER_IMAGE