name: Frontend Unit Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: investing-vue-js-app
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run test command
        run: npm run test:unit